from __future__ import annotations

import json
import shutil
import tempfile
import unittest
from pathlib import Path
from subprocess import run


ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / "tools" / "build.py"


def read_generated(path: Path):
    source = path.read_text(encoding="utf-8")
    prefix = "window.SETLIST_SONGS = "
    return source, json.loads(source[source.index(prefix) + len(prefix) :].removesuffix(";\n"))


class BuildTest(unittest.TestCase):
    def run_build(self, root: Path, *arguments: str):
        return run(
            ["/usr/bin/python3", str(BUILD), *arguments],
            cwd=root,
            check=False,
            capture_output=True,
            text=True,
        )

    def copy_inputs(self, destination: Path) -> None:
        shutil.copytree(ROOT / "charts", destination / "charts")
        (destination / "src").mkdir()
        shutil.copy(ROOT / "src" / "song-data.js", destination / "src" / "song-data.js")

    def test_build_generates_ordered_catalog_and_complete_mas_chart(self):
        completed = self.run_build(ROOT)

        self.assertEqual(0, completed.returncode, completed.stdout + completed.stderr)
        source, songs = read_generated(ROOT / "src" / "chart-data.js")
        self.assertTrue(source.startswith("// GENERATED by python3 tools/build.py"))
        self.assertEqual(
            [
                "jesus", "el-canto-de-redencion", "from-the-throne-of-god",
                "it-was-your-grace", "holy-fragance", "boast-in-the-lord",
                "covers-all-the-earth", "when-i-think-about-the-lord",
                "vuelve-mi-corazon", "accion-de-gracia",
                "avivanos-regocijate-la-alegria", "mas",
            ],
            [song["id"] for song in songs],
        )
        self.assertEqual(11, sum(song["type"] == "legacy" for song in songs))
        _, legacy_songs = read_generated(ROOT / "src" / "song-data.js")
        self.assertEqual(legacy_songs, songs[:11])
        mas = songs[-1]
        self.assertEqual(
            ("Más", "Miel San Marcos", "D", "140 BPM", "4/4"),
            (mas["title"], mas["artist"], mas["key"], mas["tempo"], mas["timeSignature"]),
        )
        self.assertEqual(22, len(mas["sections"]))
        self.assertEqual(
            [
                "intro", "verse", "tag", "pre-chorus", "tag", "chorus-1",
                "chorus-2", "intro", "verse", "tag", "pre-chorus", "chorus-1",
                "chorus-2", "instrumental", "bridge", "bridge", "bridge", "tag",
                "chorus-1", "bridge", "bridge", "ending",
            ],
            [section["id"] for section in mas["sections"]],
        )
        self.assertTrue(all(len(row["bars"]) == 4 for section in mas["sections"] for row in section["rows"]))
        self.assertEqual(["melody", "direction"], [note["type"] for note in mas["sections"][0]["rows"][1]["notes"]])
        self.assertEqual("Rakes", mas["sections"][1]["rows"][0]["notes"][0]["text"])
        self.assertEqual({"type": "chord", "chord": "3", "diamond": True}, mas["sections"][-1]["rows"][0]["bars"][3][0])

    def test_replacement_uses_id_once_and_never_title(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.copy_inputs(root)
            legacy_path = root / "src" / "song-data.js"
            legacy = legacy_path.read_text(encoding="utf-8")
            legacy = legacy.replace('"id": "jesus",\n    "title": "Jesus"', '"id": "mas",\n    "title": "Different title"', 1)
            legacy = legacy.replace('"title": "El Canto de Redencion"', '"title": "Más"', 1)
            legacy_path.write_text(legacy, encoding="utf-8")
            catalog_path = root / "charts" / "catalog.json"
            catalog = json.loads(catalog_path.read_text(encoding="utf-8"))
            catalog.remove("jesus")
            catalog_path.write_text(json.dumps(catalog), encoding="utf-8")

            completed = self.run_build(root)

            self.assertEqual(0, completed.returncode, completed.stdout + completed.stderr)
            _, songs = read_generated(root / "src" / "chart-data.js")
            self.assertEqual(1, sum(song["id"] == "mas" for song in songs))
            self.assertEqual("chart", next(song for song in songs if song["id"] == "mas")["type"])
            self.assertEqual("legacy", next(song for song in songs if song["title"] == "Más")["type"])

    def test_check_detects_drift_and_never_writes(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.copy_inputs(root)
            output = root / "src" / "chart-data.js"
            output.write_text("stale\n", encoding="utf-8")

            completed = self.run_build(root, "--check")

            self.assertNotEqual(0, completed.returncode)
            self.assertEqual("stale\n", output.read_text(encoding="utf-8"))
            self.assertIn("python3 tools/build.py", completed.stdout)

            chart_path = root / "charts" / "mas.chart"
            chart_path.write_text(
                chart_path.read_text(encoding="utf-8").replace("@key D", "@key H"),
                encoding="utf-8",
            )
            invalid = self.run_build(root, "--check")
            self.assertNotEqual(0, invalid.returncode)
            self.assertEqual("stale\n", output.read_text(encoding="utf-8"))
            self.assertIn("[E014]", invalid.stdout)

    def test_validation_error_prevents_all_writes_but_warning_generates(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.copy_inputs(root)
            output = root / "src" / "chart-data.js"
            output.write_text("sentinel\n", encoding="utf-8")
            chart_path = root / "charts" / "mas.chart"
            valid = chart_path.read_text(encoding="utf-8")
            chart_path.write_text(valid.replace("@key D", "@key H"), encoding="utf-8")

            failed = self.run_build(root)

            self.assertNotEqual(0, failed.returncode)
            self.assertEqual("sentinel\n", output.read_text(encoding="utf-8"))
            self.assertIn("[E014]", failed.stdout)

            chart_path.write_text(valid.replace(" bridge", ""), encoding="utf-8")
            succeeded = self.run_build(root)

            self.assertEqual(0, succeeded.returncode, succeeded.stdout + succeeded.stderr)
            self.assertNotEqual("sentinel\n", output.read_text(encoding="utf-8"))
            self.assertIn("[W051]", succeeded.stdout)


if __name__ == "__main__":
    unittest.main()
