from __future__ import annotations

import json
import os
import shutil
import tempfile
import unittest
from pathlib import Path
from subprocess import run
from unittest.mock import patch

from tools import build as build_module


ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / "tools" / "build.py"


def read_generated(path: Path):
    source = path.read_text(encoding="utf-8")
    prefix = "window.SETLIST_SONGS = "
    return source, json.loads(source[source.index(prefix) + len(prefix) :].removesuffix(";\n"))


class BuildTest(unittest.TestCase):
    def run_build(self, root: Path, *arguments: str):
        return run(
            ["/usr/bin/python3", str(BUILD), *arguments],
            cwd=root,
            check=False,
            capture_output=True,
            text=True,
        )

    def copy_inputs(self, destination: Path) -> None:
        shutil.copytree(ROOT / "charts", destination / "charts")
        (destination / "src").mkdir()
        for name in ("index.html", "styles.css", "script.js", "song-data.js"):
            shutil.copy(ROOT / "src" / name, destination / "src" / name)

    def test_build_generates_deterministic_self_contained_portable_viewer(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.copy_inputs(root)
            prototype = root / "setlist-viewer-v1.html"
            prototype.write_text("prior prototype\n", encoding="utf-8")

            first = self.run_build(root)
            portable = root / "setlist-viewer-portable.html"
            first_bytes = portable.read_bytes()
            second = self.run_build(root)

            self.assertEqual(0, first.returncode, first.stdout + first.stderr)
            self.assertEqual(0, second.returncode, second.stdout + second.stderr)
            self.assertEqual(first_bytes, portable.read_bytes())
            self.assertEqual("prior prototype\n", prototype.read_text(encoding="utf-8"))

            html = first_bytes.decode("utf-8")
            self.assertIn("GENERATED by python3 tools/build.py", html)
            for source in (
                "src/index.html", "src/styles.css", "src/script.js",
                "charts/catalog.json", "charts/*.chart", "src/song-data.js",
            ):
                self.assertIn(source, html)
            self.assertIn("DO NOT EDIT", html)
            self.assertNotIn('<link rel="stylesheet"', html)
            self.assertNotIn('<script src=', html)
            self.assertNotIn('type="module"', html)
            self.assertNotIn("fetch(", html)
            self.assertIn((root / "src" / "styles.css").read_text(encoding="utf-8"), html)
            self.assertIn((root / "src" / "script.js").read_text(encoding="utf-8"), html)

            _, expected_songs = read_generated(root / "src" / "chart-data.js")
            data_prefix = "window.SETLIST_SONGS = "
            embedded = html[html.index(data_prefix) + len(data_prefix) :]
            embedded = embedded[:embedded.index(";\n")]
            self.assertEqual(expected_songs, json.loads(embedded))

    def test_build_generates_ordered_catalog_and_complete_mas_chart(self):
        completed = self.run_build(ROOT)

        self.assertEqual(0, completed.returncode, completed.stdout + completed.stderr)
        source, songs = read_generated(ROOT / "src" / "chart-data.js")
        self.assertTrue(source.startswith("// GENERATED by python3 tools/build.py"))
        self.assertEqual(
            [
                "jesus", "el-canto-de-redencion", "from-the-throne-of-god",
                "it-was-your-grace", "holy-fragance", "boast-in-the-lord",
                "covers-all-the-earth", "when-i-think-about-the-lord",
                "vuelve-mi-corazon", "accion-de-gracia",
                "avivanos-regocijate-la-alegria", "mas",
            ],
            [song["id"] for song in songs],
        )
        self.assertEqual(11, sum(song["type"] == "legacy" for song in songs))
        _, legacy_songs = read_generated(ROOT / "src" / "song-data.js")
        self.assertEqual(legacy_songs, songs[:11])
        mas = songs[-1]
        self.assertEqual(
            ("Más", "Miel San Marcos", "D", "140 BPM", "4/4"),
            (mas["title"], mas["artist"], mas["key"], mas["tempo"], mas["timeSignature"]),
        )
        self.assertEqual(22, len(mas["sections"]))
        self.assertEqual(
            [
                "intro", "verse", "tag", "pre-chorus", "tag", "chorus-1",
                "chorus-2", "intro", "verse", "tag", "pre-chorus", "chorus-1",
                "chorus-2", "instrumental", "bridge", "bridge", "bridge", "tag",
                "chorus-1", "bridge", "bridge", "ending",
            ],
            [section["id"] for section in mas["sections"]],
        )
        self.assertTrue(all(len(row["bars"]) == 4 for section in mas["sections"] for row in section["rows"]))
        self.assertEqual(["melody", "direction"], [note["type"] for note in mas["sections"][0]["rows"][1]["notes"]])
        self.assertEqual("Rakes", mas["sections"][1]["rows"][0]["notes"][0]["text"])
        self.assertEqual({"type": "chord", "chord": "3", "diamond": True}, mas["sections"][-1]["rows"][0]["bars"][3][0])
        self.assertEqual(
            [1, 3, 5, 8, 10, 14, 18, 22],
            [
                occurrence
                for occurrence, section in enumerate(mas["sections"], 1)
                if not section["lyrics"]
            ],
        )
        self.assertEqual(
            [
                ["Los corazones a Tí vuelven", "Donde Tú estás allí hay libertad", "Ya no podemos resistirnos", "En Tí encontramos toda la verdad"],
                ["Un nuevo tiempo un despertar", "Tenemos hambre hambre por más"],
                ["Más de Tu presencia", "Más de Tu poder", "Un avivamiento queremos ver", "Más de Tu presencia", "Más de Tu poder", "Que no se apague el fuego", "En nuestro ser"],
                ["Los corazones a Tí vuelven", "Donde Tú estás allí hay libertad", "Ya no podemos resistirnos", "En Tí encontramos toda la verdad"],
                ["Un nuevo tiempo un despertar", "Tenemos hambre hambre por más"],
                ["Más de Tu presencia", "Más de Tu poder", "Un avivamiento queremos ver", "Más de Tu presencia", "Más de Tu poder", "Que no se apague el fuego", "En nuestro ser"],
                ["Queremos más", "Queremos más", "Queremos más de Tí Señor"],
                ["Más de Tu presencia", "Más de Tu poder", "Un avivamiento queremos ver", "Más de Tu presencia", "Más de Tu poder", "Que no se apague el fuego", "En nuestro ser"],
                ["Danzando gritando", "El rey está aquí", "Danzando gritando", "El rey está aquí"],
                ["Más de Tu presencia", "Más de Tu poder", "Un avivamiento queremos ver", "Más de Tu presencia", "Más de Tu poder", "Que no se apague el fuego", "En nuestro ser"],
                ["Danzando gritando", "El rey está aquí", "Danzando gritando", "El rey está aquí"],
                ["Que no se apague el fuego", "Fuego fuego fuego"],
                ["Queremos más deTi", "Queremos más deTi", "Queremos más deTi", "Queremos más de Ti"],
                ["Queremos más", "Queremos más", "Queremos más de Tí Señor"],
            ],
            [section["lyrics"] for section in mas["sections"] if section["lyrics"]],
        )

    def test_replacement_uses_id_once_and_never_title(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.copy_inputs(root)
            legacy_path = root / "src" / "song-data.js"
            legacy = legacy_path.read_text(encoding="utf-8")
            legacy = legacy.replace('"id": "jesus",\n    "title": "Jesus"', '"id": "mas",\n    "title": "Different title"', 1)
            legacy = legacy.replace('"title": "El Canto de Redencion"', '"title": "Más"', 1)
            legacy_path.write_text(legacy, encoding="utf-8")
            catalog_path = root / "charts" / "catalog.json"
            catalog = json.loads(catalog_path.read_text(encoding="utf-8"))
            catalog.remove("jesus")
            catalog_path.write_text(json.dumps(catalog), encoding="utf-8")

            completed = self.run_build(root)

            self.assertEqual(0, completed.returncode, completed.stdout + completed.stderr)
            _, songs = read_generated(root / "src" / "chart-data.js")
            self.assertEqual(1, sum(song["id"] == "mas" for song in songs))
            self.assertEqual("chart", next(song for song in songs if song["id"] == "mas")["type"])
            self.assertEqual("legacy", next(song for song in songs if song["title"] == "Más")["type"])

    def test_check_detects_drift_and_never_writes(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.copy_inputs(root)
            output = root / "src" / "chart-data.js"
            output.write_text("stale\n", encoding="utf-8")

            completed = self.run_build(root, "--check")

            self.assertNotEqual(0, completed.returncode)
            self.assertEqual("stale\n", output.read_text(encoding="utf-8"))
            self.assertIn("python3 tools/build.py", completed.stdout)

            chart_path = root / "charts" / "mas.chart"
            chart_path.write_text(
                chart_path.read_text(encoding="utf-8").replace("@key D", "@key H"),
                encoding="utf-8",
            )
            invalid = self.run_build(root, "--check")
            self.assertNotEqual(0, invalid.returncode)
            self.assertEqual("stale\n", output.read_text(encoding="utf-8"))
            self.assertIn("[E014]", invalid.stdout)

    def test_check_detects_portable_drift_and_writes_no_generated_output(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.copy_inputs(root)
            generated = self.run_build(root)
            self.assertEqual(0, generated.returncode, generated.stdout + generated.stderr)

            data_output = root / "src" / "chart-data.js"
            portable_output = root / "setlist-viewer-portable.html"
            data_before = data_output.read_bytes()
            portable_output.write_text("stale portable\n", encoding="utf-8")

            checked = self.run_build(root, "--check")

            self.assertNotEqual(0, checked.returncode)
            self.assertEqual(data_before, data_output.read_bytes())
            self.assertEqual("stale portable\n", portable_output.read_text(encoding="utf-8"))
            self.assertIn("setlist-viewer-portable.html", checked.stdout)
            self.assertIn("python3 tools/build.py", checked.stdout)

    def test_portable_data_is_safe_inside_an_inline_script(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.copy_inputs(root)
            legacy_path = root / "src" / "song-data.js"
            legacy_path.write_text(
                legacy_path.read_text(encoding="utf-8").replace(
                    '"title": "Jesus"',
                    '"title": "Jesus \\u003c/script\\u003e\\u003cscript\\u003eunsafe()\\u003c/script\\u003e"',
                    1,
                ),
                encoding="utf-8",
            )

            completed = self.run_build(root)

            self.assertEqual(0, completed.returncode, completed.stdout + completed.stderr)
            html = (root / "setlist-viewer-portable.html").read_text(encoding="utf-8")
            self.assertNotIn("</script><script>unsafe()</script>", html)
            self.assertIn(r"\u003c/script\u003e\u003cscript\u003eunsafe()", html)
            data_prefix = "window.SETLIST_SONGS = "
            embedded = html[html.index(data_prefix) + len(data_prefix) :]
            songs = json.loads(embedded[:embedded.index(";\n")])
            self.assertEqual("Jesus </script><script>unsafe()</script>", songs[0]["title"])

    def test_validation_error_prevents_all_writes_but_warning_generates(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.copy_inputs(root)
            output = root / "src" / "chart-data.js"
            output.write_text("sentinel\n", encoding="utf-8")
            chart_path = root / "charts" / "mas.chart"
            valid = chart_path.read_text(encoding="utf-8")
            chart_path.write_text(valid.replace("@key D", "@key H"), encoding="utf-8")

            failed = self.run_build(root)

            self.assertNotEqual(0, failed.returncode)
            self.assertEqual("sentinel\n", output.read_text(encoding="utf-8"))
            self.assertIn("[E014]", failed.stdout)

            chart_path.write_text(
                valid + "\n[unused | ZZ | Unused]\n| 1 | 1 | 1 | 1 |\n",
                encoding="utf-8",
            )
            succeeded = self.run_build(root)

            self.assertEqual(0, succeeded.returncode, succeeded.stdout + succeeded.stderr)
            self.assertNotEqual("sentinel\n", output.read_text(encoding="utf-8"))
            self.assertIn("[W051]", succeeded.stdout)

    def test_generation_failure_cannot_leave_mixed_generated_outputs(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.copy_inputs(root)
            generated = self.run_build(root)
            self.assertEqual(0, generated.returncode, generated.stdout + generated.stderr)

            data_output = root / "src" / "chart-data.js"
            data_before = data_output.read_bytes()
            portable_output = root / "setlist-viewer-portable.html"
            portable_before = portable_output.read_bytes()
            chart = root / "charts" / "mas.chart"
            chart.write_text(
                chart.read_text(encoding="utf-8").replace("@title Más", "@title Más Live"),
                encoding="utf-8",
            )

            real_replace = os.replace
            portable_failed = False

            def fail_portable_replace(source, destination):
                nonlocal portable_failed
                if Path(destination) == portable_output and not portable_failed:
                    portable_failed = True
                    raise OSError("injected portable replacement failure")
                return real_replace(source, destination)

            with patch.object(build_module.os, "replace", side_effect=fail_portable_replace):
                return_code = build_module.build(root)

            self.assertNotEqual(0, return_code)
            self.assertEqual(data_before, data_output.read_bytes())
            self.assertEqual(portable_before, portable_output.read_bytes())

    def test_generation_interruption_restores_every_generated_output(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.copy_inputs(root)
            generated = self.run_build(root)
            self.assertEqual(0, generated.returncode, generated.stdout + generated.stderr)

            data_output = root / "src" / "chart-data.js"
            portable_output = root / "setlist-viewer-portable.html"
            outputs_before = (data_output.read_bytes(), portable_output.read_bytes())
            chart = root / "charts" / "mas.chart"
            chart.write_text(
                chart.read_text(encoding="utf-8").replace("@title Más", "@title Más Live"),
                encoding="utf-8",
            )

            real_replace = os.replace
            interrupted = False

            def interrupt_portable_replace(source, destination):
                nonlocal interrupted
                if Path(destination) == portable_output and not interrupted:
                    interrupted = True
                    raise KeyboardInterrupt()
                return real_replace(source, destination)

            with self.assertRaises(KeyboardInterrupt):
                with patch.object(build_module.os, "replace", side_effect=interrupt_portable_replace):
                    build_module.build(root)

            self.assertEqual(outputs_before[0], data_output.read_bytes())
            self.assertEqual(outputs_before[1], portable_output.read_bytes())
            self.assertFalse((root / ".setlist-viewer-build-transaction.json").exists())

    def test_next_build_recovers_an_unfinished_publication(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory).resolve()
            self.copy_inputs(root)
            generated = self.run_build(root)
            self.assertEqual(0, generated.returncode, generated.stdout + generated.stderr)
            data_output = root / "src" / "chart-data.js"
            portable_output = root / "setlist-viewer-portable.html"
            outputs_before = (data_output.read_bytes(), portable_output.read_bytes())
            chart = root / "charts" / "mas.chart"
            chart.write_text(
                chart.read_text(encoding="utf-8").replace("@title Más", "@title Más Live"),
                encoding="utf-8",
            )
            crash_script = """
import os
import sys
from pathlib import Path
from unittest.mock import patch
from tools import build

root = Path(sys.argv[1])
portable = root / "setlist-viewer-portable.html"
real_replace = os.replace

def stop_after_first_publish(source, destination):
    if Path(destination) == portable:
        os._exit(91)
    return real_replace(source, destination)

with patch.object(build.os, "replace", side_effect=stop_after_first_publish):
    build.build(root)
"""

            interrupted = run(
                ["/usr/bin/python3", "-c", crash_script, str(root)],
                cwd=ROOT,
                check=False,
            )
            self.assertEqual(91, interrupted.returncode)
            marker = root / ".setlist-viewer-build-transaction.json"
            self.assertTrue(marker.is_file())

            chart.write_text(
                chart.read_text(encoding="utf-8").replace("@key D", "@key H"),
                encoding="utf-8",
            )
            invalid = self.run_build(root)
            self.assertNotEqual(0, invalid.returncode)
            self.assertFalse(marker.exists())
            self.assertEqual(outputs_before[0], data_output.read_bytes())
            self.assertEqual(outputs_before[1], portable_output.read_bytes())

            chart.write_text(
                chart.read_text(encoding="utf-8").replace("@key H", "@key D"),
                encoding="utf-8",
            )

            recovered = self.run_build(root)

            self.assertEqual(0, recovered.returncode, recovered.stdout + recovered.stderr)
            self.assertFalse(marker.exists())
            self.assertEqual(0, self.run_build(root, "--check").returncode)
            self.assertIn("Más Live", (root / "src" / "chart-data.js").read_text(encoding="utf-8"))
            self.assertIn("Más Live", (root / "setlist-viewer-portable.html").read_text(encoding="utf-8"))

    def test_rollback_failure_preserves_backups_for_next_build_recovery(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory).resolve()
            self.copy_inputs(root)
            self.assertEqual(0, self.run_build(root).returncode)
            data_output = root / "src" / "chart-data.js"
            portable_output = root / "setlist-viewer-portable.html"
            outputs_before = (data_output.read_bytes(), portable_output.read_bytes())
            chart = root / "charts" / "mas.chart"
            chart.write_text(
                chart.read_text(encoding="utf-8").replace("@title Más", "@title Más Live"),
                encoding="utf-8",
            )

            real_replace = os.replace
            publication_failed = False
            rollback_failed = False

            def fail_publication_and_rollback(source, destination):
                nonlocal publication_failed, rollback_failed
                destination = Path(destination)
                if destination == portable_output and not publication_failed:
                    publication_failed = True
                    raise OSError("injected publication failure")
                if publication_failed and destination == data_output and not rollback_failed:
                    rollback_failed = True
                    raise OSError("injected rollback failure")
                return real_replace(source, destination)

            with patch.object(build_module.os, "replace", side_effect=fail_publication_and_rollback):
                return_code = build_module.build(root)
            self.assertNotEqual(0, return_code)
            marker = root / ".setlist-viewer-build-transaction.json"
            entries = json.loads(marker.read_text(encoding="utf-8"))
            self.assertTrue(all(Path(entry["backup"]).is_file() for entry in entries))

            chart.write_text(
                chart.read_text(encoding="utf-8").replace("@key D", "@key H"),
                encoding="utf-8",
            )
            invalid = self.run_build(root)

            self.assertNotEqual(0, invalid.returncode)
            self.assertFalse(marker.exists())
            self.assertEqual(outputs_before[0], data_output.read_bytes())
            self.assertEqual(outputs_before[1], portable_output.read_bytes())


if __name__ == "__main__":
    unittest.main()
