#!/usr/bin/env python3
"""Generate deterministic browser data from canonical Setlist Viewer inputs."""

from __future__ import annotations

import argparse
import json
import os
import re
import tempfile
from pathlib import Path

from chart_validator import Bar, BarEvent, Chart, ChartRow, RowNote, Section, validate_chart


HEADER = (
    "// GENERATED by python3 tools/build.py from charts/catalog.json, "
    "charts/*.chart, and src/song-data.js.\n"
    "// DO NOT EDIT: change the canonical inputs and rebuild.\n"
)


class BuildError(Exception):
    pass


def first_duplicate(values: list[str]) -> str | None:
    seen: set[str] = set()
    for value in values:
        if value in seen:
            return value
        seen.add(value)
    return None


def load_legacy_songs(path: Path) -> list[dict[str, object]]:
    try:
        source = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        raise BuildError(f"{path}: cannot read Legacy Songs: {error}") from error
    match = re.fullmatch(r"window\.SETLIST_SONGS = (.*);\s*", source, re.DOTALL)
    if not match:
        raise BuildError(f"{path}: expected one JSON-compatible window.SETLIST_SONGS assignment")
    try:
        songs = json.loads(match.group(1))
    except json.JSONDecodeError as error:
        raise BuildError(f"{path}:{error.lineno}:{error.colno}: invalid Legacy Song JSON") from error
    if not isinstance(songs, list) or not all(isinstance(song, dict) for song in songs):
        raise BuildError(f"{path}: Legacy Songs must be an array of objects")
    ids = [song.get("id") for song in songs]
    if any(not isinstance(song_id, str) or not song_id for song_id in ids):
        raise BuildError(f"{path}: every Legacy Song requires a string ID")
    duplicate = first_duplicate(ids)
    if duplicate:
        raise BuildError(f"{path}: duplicate Legacy Song ID '{duplicate}'")
    return songs


def load_catalog(path: Path) -> list[str]:
    try:
        catalog = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise BuildError(f"{path}: invalid catalog: {error}") from error
    if not isinstance(catalog, list) or not all(isinstance(song_id, str) for song_id in catalog):
        raise BuildError(f"{path}: catalog must be an array of Song IDs")
    duplicate = first_duplicate(catalog)
    if duplicate:
        raise BuildError(f"{path}: duplicate catalog Song ID '{duplicate}'")
    return catalog


def event_data(event: BarEvent) -> dict[str, object]:
    data: dict[str, object] = {"type": event.kind}
    if event.chord is not None:
        data["chord"] = event.chord
    if event.beats is not None:
        data["beats"] = event.beats
    if event.diamond:
        data["diamond"] = True
    return data


def bar_data(bar: Bar | None) -> list[dict[str, object]] | None:
    if bar is None:
        return None
    return [event_data(event) for event in bar.events]


def note_data(note: RowNote) -> dict[str, object]:
    if note.kind == "direction":
        return {"type": "direction", "text": note.value}
    return {"type": "melody", "fragments": list(note.value)}


def row_data(row: ChartRow) -> dict[str, object]:
    return {
        "bars": [bar_data(bar) for bar in row.slots],
        "notes": [note_data(note) for note in row.notes],
    }


def section_data(section: Section) -> dict[str, object]:
    data: dict[str, object] = {
        "id": section.id,
        "code": section.code,
        "name": section.name,
        "rows": [row_data(row) for row in section.rows],
    }
    if section.ordinal is not None:
        data["ordinal"] = section.ordinal
    return data


def chart_data(song_id: str, chart: Chart) -> dict[str, object]:
    sections = {section.id: section for section in chart.sections}
    metadata = chart.metadata
    data: dict[str, object] = {
        "type": "chart",
        "id": song_id,
        "title": metadata["title"],
        "artist": metadata["artist"],
        "tempo": f'{metadata["tempo"]} BPM',
        "key": metadata["key"],
        "timeSignature": metadata["time"],
        "sections": [section_data(sections[section_id]) for section_id in chart.arrangement],
    }
    if "lead-vocal" in metadata:
        data["leadVocal"] = metadata["lead-vocal"]
    if "details" in metadata:
        data["details"] = metadata["details"]
    return data


def generated_source(songs: list[dict[str, object]]) -> str:
    return HEADER + "window.SETLIST_SONGS = " + json.dumps(
        songs, ensure_ascii=False, indent=2, separators=(",", ": ")
    ) + ";\n"


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_path, path)
    finally:
        if temporary_path.exists():
            temporary_path.unlink()


def build(root: Path, check: bool = False) -> int:
    try:
        legacy_songs = load_legacy_songs(root / "src" / "song-data.js")
        catalog = load_catalog(root / "charts" / "catalog.json")
    except BuildError as error:
        print(error)
        return 1

    chart_paths = sorted((root / "charts").glob("*.chart"))
    results = [(path, validate_chart(path)) for path in chart_paths]
    for _, result in results:
        for diagnostic in result.diagnostics:
            print(diagnostic.format())
    if any(result.errors for _, result in results):
        return 1

    charts = {
        path.stem: chart_data(path.stem, result.chart)
        for path, result in results
        if result.chart is not None
    }
    legacy_by_id = {song["id"]: song for song in legacy_songs}
    available_ids = set(legacy_by_id) | set(charts)
    missing = [song_id for song_id in catalog if song_id not in available_ids]
    omitted = sorted(available_ids - set(catalog))
    if missing or omitted:
        if missing:
            print(f"charts/catalog.json: unknown Song ID '{missing[0]}'")
        if omitted:
            print(f"charts/catalog.json: missing Song ID '{omitted[0]}'")
        return 1

    songs = [charts.get(song_id, legacy_by_id.get(song_id)) for song_id in catalog]
    output = root / "src" / "chart-data.js"
    expected = generated_source(songs)
    if check:
        try:
            actual = output.read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            actual = None
        if actual != expected:
            print(f"{output}: generated data is missing or stale; run python3 tools/build.py")
            return 1
        return 0

    atomic_write(output, expected)
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="validate and detect drift without writing")
    arguments = parser.parse_args(argv)
    return build(Path.cwd(), arguments.check)


if __name__ == "__main__":
    raise SystemExit(main())
