#!/usr/bin/env python3
"""Generate deterministic browser data from canonical Setlist Viewer inputs."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import tempfile
from pathlib import Path

if __package__:
    from .chart_validator import Bar, BarEvent, Chart, ChartRow, RowNote, Section, validate_chart
else:
    from chart_validator import Bar, BarEvent, Chart, ChartRow, RowNote, Section, validate_chart


HEADER = (
    "// GENERATED by python3 tools/build.py from charts/catalog.json, "
    "charts/*.chart, and src/song-data.js.\n"
    "// DO NOT EDIT: change the canonical inputs and rebuild.\n"
)
PORTABLE_HEADER = (
    "<!-- GENERATED by python3 tools/build.py from src/index.html, src/styles.css, "
    "src/script.js, charts/catalog.json, charts/*.chart, and src/song-data.js.\n"
    "DO NOT EDIT: change the canonical inputs and rebuild. -->\n"
)


class BuildError(Exception):
    pass


def first_duplicate(values: list[str]) -> str | None:
    seen: set[str] = set()
    for value in values:
        if value in seen:
            return value
        seen.add(value)
    return None


def load_legacy_songs(path: Path) -> list[dict[str, object]]:
    try:
        source = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        raise BuildError(f"{path}: cannot read Legacy Songs: {error}") from error
    match = re.fullmatch(r"window\.SETLIST_SONGS = (.*);\s*", source, re.DOTALL)
    if not match:
        raise BuildError(f"{path}: expected one JSON-compatible window.SETLIST_SONGS assignment")
    try:
        songs = json.loads(match.group(1))
    except json.JSONDecodeError as error:
        raise BuildError(f"{path}:{error.lineno}:{error.colno}: invalid Legacy Song JSON") from error
    if not isinstance(songs, list) or not all(isinstance(song, dict) for song in songs):
        raise BuildError(f"{path}: Legacy Songs must be an array of objects")
    ids = [song.get("id") for song in songs]
    if any(not isinstance(song_id, str) or not song_id for song_id in ids):
        raise BuildError(f"{path}: every Legacy Song requires a string ID")
    duplicate = first_duplicate(ids)
    if duplicate:
        raise BuildError(f"{path}: duplicate Legacy Song ID '{duplicate}'")
    return songs


def load_catalog(path: Path) -> list[str]:
    try:
        catalog = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise BuildError(f"{path}: invalid catalog: {error}") from error
    if not isinstance(catalog, list) or not all(isinstance(song_id, str) for song_id in catalog):
        raise BuildError(f"{path}: catalog must be an array of Song IDs")
    duplicate = first_duplicate(catalog)
    if duplicate:
        raise BuildError(f"{path}: duplicate catalog Song ID '{duplicate}'")
    return catalog


def event_data(event: BarEvent) -> dict[str, object]:
    data: dict[str, object] = {"type": event.kind}
    if event.chord is not None:
        data["chord"] = event.chord
    if event.beats is not None:
        data["beats"] = event.beats
    if event.diamond:
        data["diamond"] = True
    return data


def bar_data(bar: Bar | None) -> list[dict[str, object]] | None:
    if bar is None:
        return None
    return [event_data(event) for event in bar.events]


def note_data(note: RowNote) -> dict[str, object]:
    if note.kind == "direction":
        return {"type": "direction", "text": note.value}
    return {"type": "melody", "fragments": list(note.value)}


def row_data(row: ChartRow) -> dict[str, object]:
    return {
        "bars": [bar_data(bar) for bar in row.slots],
        "notes": [note_data(note) for note in row.notes],
    }


def section_data(section: Section) -> dict[str, object]:
    data: dict[str, object] = {
        "id": section.id,
        "code": section.code,
        "name": section.name,
        "rows": [row_data(row) for row in section.rows],
    }
    if section.ordinal is not None:
        data["ordinal"] = section.ordinal
    return data


def chart_data(song_id: str, chart: Chart) -> dict[str, object]:
    sections = {section.id: section for section in chart.sections}
    metadata = chart.metadata
    data: dict[str, object] = {
        "type": "chart",
        "id": song_id,
        "title": metadata["title"],
        "artist": metadata["artist"],
        "tempo": f'{metadata["tempo"]} BPM',
        "key": metadata["key"],
        "timeSignature": metadata["time"],
        "sections": [section_data(sections[section_id]) for section_id in chart.arrangement],
    }
    if "lead-vocal" in metadata:
        data["leadVocal"] = metadata["lead-vocal"]
    if "details" in metadata:
        data["details"] = metadata["details"]
    return data


def serialized_catalog(songs: list[dict[str, object]]) -> str:
    return json.dumps(
        songs, ensure_ascii=False, indent=2, separators=(",", ": ")
    )


def catalog_assignment(serialized: str) -> str:
    return "window.SETLIST_SONGS = " + serialized + ";\n"


def generated_source(songs: list[dict[str, object]]) -> str:
    return HEADER + catalog_assignment(serialized_catalog(songs))


def portable_data_source(songs: list[dict[str, object]]) -> str:
    data = serialized_catalog(songs)
    for character, escape in (
        ("&", r"\u0026"),
        ("<", r"\u003c"),
        (">", r"\u003e"),
        ("\u2028", r"\u2028"),
        ("\u2029", r"\u2029"),
    ):
        data = data.replace(character, escape)
    return catalog_assignment(data)


def portable_source(
    index_source: str,
    styles_source: str,
    script_source: str,
    songs: list[dict[str, object]],
) -> str:
    stylesheet = '<link rel="stylesheet" href="styles.css">'
    scripts = '  <script src="chart-data.js"></script>\n  <script src="script.js"></script>'
    if index_source.count(stylesheet) != 1 or index_source.count(scripts) != 1:
        raise BuildError("src/index.html: expected canonical stylesheet and script references")
    document = index_source.replace(stylesheet, "<style>\n" + styles_source + "  </style>")
    inline_scripts = (
        "  <script>\n"
        + portable_data_source(songs)
        + "  </script>\n"
        + "  <script>\n"
        + script_source
        + "  </script>"
    )
    return PORTABLE_HEADER + document.replace(scripts, inline_scripts)


def read_canonical_source(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        raise BuildError(f"{path}: cannot read canonical source: {error}") from error


def transaction_path_for(outputs: list[tuple[Path, str]]) -> Path:
    common_parent = Path(os.path.commonpath([str(path.parent) for path, _ in outputs]))
    return common_parent / ".setlist-viewer-build-transaction.json"


def write_transaction(path: Path, backups: list[tuple[Path, Path | None]]) -> None:
    content = json.dumps(
        [
            {"output": str(output), "backup": str(backup) if backup is not None else None}
            for output, backup in backups
        ],
        indent=2,
    ) + "\n"
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_path, path)
    finally:
        if temporary_path.exists():
            temporary_path.unlink()


def restore_transaction(path: Path, output_paths: list[Path]) -> None:
    try:
        entries = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise BuildError(f"{path}: cannot recover interrupted generation: {error}") from error
    if (
        not isinstance(entries, list)
        or not all(isinstance(entry, dict) for entry in entries)
        or [entry.get("output") for entry in entries]
        != [str(output) for output in output_paths]
    ):
        raise BuildError(f"{path}: interrupted generation does not match requested outputs")

    restore_paths: list[tuple[Path, Path | None, Path | None]] = []
    try:
        for output, entry in zip(output_paths, entries):
            backup_name = entry.get("backup")
            if backup_name is None:
                restore_paths.append((output, None, None))
                continue
            backup = Path(backup_name)
            if (
                backup.parent != output.parent
                or not backup.name.startswith(f".{output.name}.backup.")
                or not backup.is_file()
            ):
                raise BuildError(f"{path}: missing recovery backup for {output}")
            descriptor, restore_name = tempfile.mkstemp(
                prefix=f".{output.name}.restore.", dir=output.parent
            )
            os.close(descriptor)
            restore = Path(restore_name)
            shutil.copy2(backup, restore)
            restore_paths.append((output, backup, restore))

        for output, _, restore in restore_paths:
            if restore is None:
                if output.exists():
                    output.unlink()
            else:
                os.replace(restore, output)

        path.unlink()
        for _, backup, _ in restore_paths:
            if backup is not None and backup.exists():
                backup.unlink()
    except BuildError:
        raise
    except OSError as error:
        raise BuildError(f"{path}: cannot recover interrupted generation: {error}") from error
    finally:
        for _, _, restore in restore_paths:
            if restore is not None and restore.exists():
                restore.unlink()


def atomic_write_outputs(outputs: list[tuple[Path, str]]) -> None:
    temporary_paths: list[tuple[Path, Path]] = []
    backup_paths: list[tuple[Path, Path | None]] = []
    transaction_path = transaction_path_for(outputs)
    try:
        if transaction_path.exists():
            restore_transaction(transaction_path, [path for path, _ in outputs])

        for path, _ in outputs:
            if path.exists() and not path.is_file():
                raise BuildError(f"{path}: generated output target is not a file")
            path.parent.mkdir(parents=True, exist_ok=True)

        for path, content in outputs:
            descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
            temporary_path = Path(temporary_name)
            temporary_paths.append((path, temporary_path))
            with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
                handle.write(content)
                handle.flush()
                os.fsync(handle.fileno())

        for path, _ in outputs:
            if not path.exists():
                backup_paths.append((path, None))
                continue
            descriptor, backup_name = tempfile.mkstemp(prefix=f".{path.name}.backup.", dir=path.parent)
            os.close(descriptor)
            backup_path = Path(backup_name)
            shutil.copy2(path, backup_path)
            backup_paths.append((path, backup_path))

        write_transaction(transaction_path, backup_paths)
        try:
            for path, temporary_path in temporary_paths:
                os.replace(temporary_path, path)
            transaction_path.unlink()
        except BaseException as error:
            try:
                restore_transaction(transaction_path, [path for path, _ in outputs])
            except BuildError as rollback_error:
                raise BuildError(
                    f"cannot atomically generate outputs: {error}; rollback failed: {rollback_error}"
                ) from error
            if isinstance(error, OSError):
                raise BuildError(
                    f"cannot atomically generate outputs: {error}; previous outputs restored"
                ) from error
            raise
    except BuildError:
        raise
    except OSError as error:
        raise BuildError(f"cannot atomically generate outputs: {error}") from error
    finally:
        for _, temporary_path in temporary_paths:
            if temporary_path.exists():
                temporary_path.unlink()
        if not transaction_path.exists():
            for _, backup_path in backup_paths:
                if backup_path is not None and backup_path.exists():
                    backup_path.unlink()


def build(root: Path, check: bool = False) -> int:
    data_output = root / "src" / "chart-data.js"
    portable_output = root / "setlist-viewer-portable.html"
    generated_outputs = [(data_output, ""), (portable_output, "")]
    transaction_path = transaction_path_for(generated_outputs)
    if not check and transaction_path.exists():
        try:
            restore_transaction(transaction_path, [data_output, portable_output])
        except BuildError as error:
            print(error)
            return 1

    try:
        legacy_songs = load_legacy_songs(root / "src" / "song-data.js")
        catalog = load_catalog(root / "charts" / "catalog.json")
        index_source = read_canonical_source(root / "src" / "index.html")
        styles_source = read_canonical_source(root / "src" / "styles.css")
        script_source = read_canonical_source(root / "src" / "script.js")
    except BuildError as error:
        print(error)
        return 1

    chart_paths = sorted((root / "charts").glob("*.chart"))
    results = [(path, validate_chart(path)) for path in chart_paths]
    for _, result in results:
        for diagnostic in result.diagnostics:
            print(diagnostic.format())
    if any(result.errors for _, result in results):
        return 1

    charts = {
        path.stem: chart_data(path.stem, result.chart)
        for path, result in results
        if result.chart is not None
    }
    legacy_by_id = {song["id"]: song for song in legacy_songs}
    available_ids = set(legacy_by_id) | set(charts)
    missing = [song_id for song_id in catalog if song_id not in available_ids]
    omitted = sorted(available_ids - set(catalog))
    if missing or omitted:
        if missing:
            print(f"charts/catalog.json: unknown Song ID '{missing[0]}'")
        if omitted:
            print(f"charts/catalog.json: missing Song ID '{omitted[0]}'")
        return 1

    songs = [charts.get(song_id, legacy_by_id.get(song_id)) for song_id in catalog]
    expected_data = generated_source(songs)
    try:
        expected_portable = portable_source(index_source, styles_source, script_source, songs)
    except BuildError as error:
        print(error)
        return 1
    if check:
        stale_outputs = []
        for output, expected in (
            (data_output, expected_data),
            (portable_output, expected_portable),
        ):
            try:
                actual = output.read_text(encoding="utf-8")
            except (OSError, UnicodeError):
                actual = None
            if actual != expected:
                stale_outputs.append(output)
        if stale_outputs:
            for output in stale_outputs:
                print(f"{output}: generated output is missing or stale; run python3 tools/build.py")
            return 1
        return 0

    try:
        atomic_write_outputs(
            [(data_output, expected_data), (portable_output, expected_portable)]
        )
    except BuildError as error:
        print(error)
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="validate and detect drift without writing")
    arguments = parser.parse_args(argv)
    return build(Path.cwd(), arguments.check)


if __name__ == "__main__":
    raise SystemExit(main())
