// GENERATED by python3 tools/build.py from charts/catalog.json, charts/*.chart, and src/song-data.js.
// DO NOT EDIT: change the canonical inputs and rebuild.
window.SETLIST_SONGS = [
  {
    "type": "legacy",
    "id": "jesus",
    "title": "Jesus",
    "tempo": "113 BPM",
    "key": "A",
    "leadVocal": "Matthew Morales",
    "details": "Piano intro. Keyboard lines during the intro.",
    "detailsEmpty": false,
    "sections": [
      {
        "name": "Intro"
      },
      {
        "name": "Intro"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Turnaround"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Turnaround"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Outro"
      }
    ]
  },
  {
    "type": "legacy",
    "id": "el-canto-de-redencion",
    "title": "El Canto de Redencion",
    "tempo": "128 BPM",
    "key": "D",
    "leadVocal": "Jhonny Rez",
    "details": "Percussion intro. Electric guitar comes in right after.",
    "detailsEmpty": false,
    "sections": [
      {
        "name": "Intro"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Turnaround"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Instrumental"
      },
      {
        "name": "Instrumental"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Tag"
      },
      {
        "name": "Tag"
      },
      {
        "name": "Instrumental"
      },
      {
        "name": "Outro"
      }
    ]
  },
  {
    "type": "legacy",
    "id": "from-the-throne-of-god",
    "title": "From the Throne of God",
    "tempo": "133 BPM",
    "key": "D-flat",
    "leadVocal": "Marya Adedimeji",
    "details": "Brass intro. Bass solo before the bridge section.",
    "detailsEmpty": false,
    "sections": [
      {
        "name": "Intro"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Tag"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Post-Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Instrumental"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge 2"
      },
      {
        "name": "Bridge 2"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Post-Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Outro"
      }
    ]
  },
  {
    "type": "legacy",
    "id": "it-was-your-grace",
    "title": "It Was Your Grace",
    "tempo": "146 BPM",
    "key": "A",
    "leadVocal": "Waleska Morales",
    "details": "Brass intro. Full-band hits on Verse 2.",
    "detailsEmpty": false,
    "sections": [
      {
        "name": "Intro"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Pre-Chorus"
      },
      {
        "name": "Pre-Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Instrumental"
      },
      {
        "name": "Verse 2"
      },
      {
        "name": "Verse 2"
      },
      {
        "name": "Pre-Chorus"
      },
      {
        "name": "Pre-Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Instrumental"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Outro"
      }
    ]
  },
  {
    "type": "legacy",
    "id": "holy-fragance",
    "title": "Holy Fragance",
    "tempo": "114 BPM",
    "key": "D",
    "leadVocal": "Paloma Ramos",
    "details": "Eg / keys intro",
    "detailsEmpty": false,
    "sections": [
      {
        "name": "Intro"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Pre-Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Turnaround"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Pre-Chorus"
      },
      {
        "name": "Pre-Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Instrumental"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge 2"
      },
      {
        "name": "Bridge 2"
      },
      {
        "name": "Tag"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Tag"
      },
      {
        "name": "Chorus"
      }
    ]
  },
  {
    "type": "legacy",
    "id": "boast-in-the-lord",
    "title": "Boast in the Lord",
    "tempo": "96 BPM",
    "key": "A",
    "leadVocal": "Nick Torres",
    "details": "Drum intro.",
    "detailsEmpty": false,
    "sections": [
      {
        "name": "Intro"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Tag"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Instrumental"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Tag"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Instrumental"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Tag"
      },
      {
        "name": "Tag"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Chorus"
      }
    ]
  },
  {
    "type": "legacy",
    "id": "covers-all-the-earth",
    "title": "Covers All the Earth",
    "tempo": "150 BPM",
    "key": "D",
    "leadVocal": "Genock",
    "details": "No additional detail shown in the sheet.",
    "detailsEmpty": true,
    "sections": [
      {
        "name": "Intro"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Turnaround"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Tag"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Instrumental"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Tag"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Tag"
      },
      {
        "name": "Outro"
      }
    ]
  },
  {
    "type": "legacy",
    "id": "when-i-think-about-the-lord",
    "title": "When I Think About the Lord",
    "tempo": "BPM: Not shown",
    "key": "D / E",
    "leadVocal": "Josh / Marya",
    "details": "Verse 1 is led by Josh. Verse 2 and onward are led by Marya.",
    "detailsEmpty": false,
    "sections": [
      {
        "name": "Flow"
      }
    ]
  },
  {
    "type": "legacy",
    "id": "vuelve-mi-corazon",
    "title": "Vuelve Mi Corazon",
    "tempo": "103 BPM",
    "key": "G",
    "leadVocal": "Genock",
    "details": "No additional detail shown in the sheet.",
    "detailsEmpty": true,
    "sections": [
      {
        "name": "Intro"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Verse 2"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Turnaround"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Post-Chorus"
      },
      {
        "name": "Turnaround"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Tag"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Post-Chorus"
      },
      {
        "name": "Outro"
      }
    ]
  },
  {
    "type": "legacy",
    "id": "accion-de-gracia",
    "title": "Accion de Gracia",
    "tempo": "110 BPM",
    "key": "F",
    "leadVocal": "Miel San Marcos",
    "details": "No additional detail shown in the sheet.",
    "detailsEmpty": true,
    "sections": [
      {
        "name": "Intro"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Verse 2"
      },
      {
        "name": "Pre-Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Turnaround"
      },
      {
        "name": "Verse"
      },
      {
        "name": "Pre-Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Turnaround"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Bridge"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Chorus"
      },
      {
        "name": "Outro"
      }
    ]
  },
  {
    "type": "legacy",
    "id": "avivanos-regocijate-la-alegria",
    "title": "Avivanos - Regocijate - La Alegria",
    "tempo": "155 BPM",
    "key": "C / G / B-flat / E-flat",
    "leadVocal": "Miel San Marcos",
    "details": "No additional detail shown in the sheet.",
    "detailsEmpty": true,
    "sections": [
      {
        "name": "Medley"
      }
    ]
  },
  {
    "type": "chart",
    "id": "mas",
    "title": "Más",
    "artist": "Miel San Marcos",
    "tempo": "140 BPM",
    "key": "D",
    "timeSignature": "4/4",
    "sections": [
      {
        "id": "intro",
        "code": "IN",
        "name": "Intro",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "17 65",
                  "32 12",
                  "17 65",
                  "5156 5"
                ]
              }
            ]
          },
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "17 65",
                  "32 12",
                  "17 65",
                  "5156 5"
                ]
              },
              {
                "type": "direction",
                "text": "oct ↑"
              }
            ]
          }
        ]
      },
      {
        "id": "verse",
        "code": "VS",
        "name": "Verse",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "direction",
                "text": "Rakes"
              }
            ]
          },
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": []
          }
        ]
      },
      {
        "id": "tag",
        "code": "TG",
        "name": "Tag",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ],
              null,
              null,
              null
            ],
            "notes": []
          }
        ]
      },
      {
        "id": "pre-chorus",
        "code": "PC",
        "name": "Pre-Chorus",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "17 65",
                  "32 12",
                  "17 65",
                  "5156 5"
                ]
              }
            ]
          },
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "17 65",
                  "32 12",
                  "17 65",
                  "5156 5"
                ]
              },
              {
                "type": "direction",
                "text": "oct ↑"
              }
            ]
          }
        ]
      },
      {
        "id": "tag",
        "code": "TG",
        "name": "Tag",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ],
              null,
              null,
              null
            ],
            "notes": []
          }
        ]
      },
      {
        "id": "chorus-1",
        "code": "CH",
        "name": "Chorus",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "6 3",
                  "6 -",
                  "6 3",
                  "7 -"
                ]
              }
            ]
          },
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "6 3",
                  "6 -",
                  "6 3",
                  "7 -"
                ]
              }
            ]
          }
        ],
        "ordinal": 1
      },
      {
        "id": "chorus-2",
        "code": "CH",
        "name": "Chorus",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "656 3",
                  "656 3",
                  "656 3",
                  "7"
                ]
              }
            ]
          },
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "656 3",
                  "656 3",
                  "656 3",
                  "7"
                ]
              }
            ]
          }
        ],
        "ordinal": 2
      },
      {
        "id": "intro",
        "code": "IN",
        "name": "Intro",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "17 65",
                  "32 12",
                  "17 65",
                  "5156 5"
                ]
              }
            ]
          },
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "17 65",
                  "32 12",
                  "17 65",
                  "5156 5"
                ]
              },
              {
                "type": "direction",
                "text": "oct ↑"
              }
            ]
          }
        ]
      },
      {
        "id": "verse",
        "code": "VS",
        "name": "Verse",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "direction",
                "text": "Rakes"
              }
            ]
          },
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": []
          }
        ]
      },
      {
        "id": "tag",
        "code": "TG",
        "name": "Tag",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ],
              null,
              null,
              null
            ],
            "notes": []
          }
        ]
      },
      {
        "id": "pre-chorus",
        "code": "PC",
        "name": "Pre-Chorus",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "17 65",
                  "32 12",
                  "17 65",
                  "5156 5"
                ]
              }
            ]
          },
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "17 65",
                  "32 12",
                  "17 65",
                  "5156 5"
                ]
              },
              {
                "type": "direction",
                "text": "oct ↑"
              }
            ]
          }
        ]
      },
      {
        "id": "chorus-1",
        "code": "CH",
        "name": "Chorus",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "6 3",
                  "6 -",
                  "6 3",
                  "7 -"
                ]
              }
            ]
          },
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "6 3",
                  "6 -",
                  "6 3",
                  "7 -"
                ]
              }
            ]
          }
        ],
        "ordinal": 1
      },
      {
        "id": "chorus-2",
        "code": "CH",
        "name": "Chorus",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "656 3",
                  "656 3",
                  "656 3",
                  "7"
                ]
              }
            ]
          },
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "656 3",
                  "656 3",
                  "656 3",
                  "7"
                ]
              }
            ]
          }
        ],
        "ordinal": 2
      },
      {
        "id": "instrumental",
        "code": "IS",
        "name": "Instrumental",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "265 61",
                  "3322 1265",
                  "265 61",
                  "3322 3511"
                ]
              }
            ]
          },
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "265 61",
                  "3322 1265",
                  "265 61",
                  "3322 3511"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "bridge",
        "code": "BR",
        "name": "Bridge",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "5"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "1/3"
                }
              ]
            ],
            "notes": []
          },
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "5"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "1/3"
                }
              ]
            ],
            "notes": []
          }
        ]
      },
      {
        "id": "bridge",
        "code": "BR",
        "name": "Bridge",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "5"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "1/3"
                }
              ]
            ],
            "notes": []
          },
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "5"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "1/3"
                }
              ]
            ],
            "notes": []
          }
        ]
      },
      {
        "id": "bridge",
        "code": "BR",
        "name": "Bridge",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "5"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "1/3"
                }
              ]
            ],
            "notes": []
          },
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "5"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "1/3"
                }
              ]
            ],
            "notes": []
          }
        ]
      },
      {
        "id": "tag",
        "code": "TG",
        "name": "Tag",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ],
              null,
              null,
              null
            ],
            "notes": []
          }
        ]
      },
      {
        "id": "chorus-1",
        "code": "CH",
        "name": "Chorus",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "6 3",
                  "6 -",
                  "6 3",
                  "7 -"
                ]
              }
            ]
          },
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ]
            ],
            "notes": [
              {
                "type": "melody",
                "fragments": [
                  "6 3",
                  "6 -",
                  "6 3",
                  "7 -"
                ]
              }
            ]
          }
        ],
        "ordinal": 1
      },
      {
        "id": "bridge",
        "code": "BR",
        "name": "Bridge",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "5"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "1/3"
                }
              ]
            ],
            "notes": []
          },
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "5"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "1/3"
                }
              ]
            ],
            "notes": []
          }
        ]
      },
      {
        "id": "bridge",
        "code": "BR",
        "name": "Bridge",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "5"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "1/3"
                }
              ]
            ],
            "notes": []
          },
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "5"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "6"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "1/3"
                }
              ]
            ],
            "notes": []
          }
        ]
      },
      {
        "id": "ending",
        "code": "EN",
        "name": "Ending",
        "rows": [
          {
            "bars": [
              [
                {
                  "type": "chord",
                  "chord": "2"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "4"
                }
              ],
              [
                {
                  "type": "chord",
                  "chord": "3",
                  "diamond": true
                }
              ]
            ],
            "notes": []
          }
        ]
      }
    ]
  }
];
